dndwebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('games/', include('game.urls'))
]

game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('create/<int:gameID>/', views.create_Character, name='create_character'),
    path('createGame/', views.create_Game, name="create_game"),
    path('chat/<int:gameID>', views.chat, name="chat"),
    path('list/', views.list, name="list"),
    path('detail/<int:gameID>', views.detail, name="detail"),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signin/', views.home, name="signin"),
    path('start/', views.start, name="start"),
    path('', views.redir, name="redirect"),
]

game/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Game(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=50, default="")
    setting = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name


class Character(models.Model):
    ORIGIN_CHOICES = {
        'origin1': 'origin1',
        'origin2': 'origin2',
        'origin3': 'origin3',
        'origin4': 'origin4',
    }

    GENDER_CHOICES = {
        'male': 'male',
        'female': 'female',
        'other': 'other',
    }

    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, default="")
    origin = models.CharField(max_length=7, choices=ORIGIN_CHOICES, default='origin1')
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, default='male')
    is_user = models.BooleanField(default=False)
    plot = models.CharField(max_length=500, default="")
    stat = models.JSONField(default=dict)
    

    def __str__(self):
        return self.name

class Log(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

home/models.py
from django.db import models

# Create your models here.

game/forms.py
from django import forms
from .models import Character

class CharacterForm(forms.ModelForm):
    class Meta:
        model = Character
        fields = ['name', 'origin', 'gender', 'plot']
        

game/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .forms import CharacterForm
from .models import *
import gemini.functions as geminiResponse

# Create your views here.

@login_required
def create_Character(request, gameID):
    game = Game.objects.get(id=gameID)
    user_character_cnt = Character.objects.filter(game=game, is_user=True).count()
    if user_character_cnt >= 1:
        return redirect('game:chat', gameID=gameID)
    form = CharacterForm(request.POST or None)
    if form.is_valid():
        character = form.save(commit=False)
        response = geminiResponse.create_stat(name=character.name, origin=character.origin, gender=character.gender, plot=character.plot)
        character.game= game
        character.is_user = True
        character.stat = response['stats']
        character.save()
        game.name = f"{character.name}'s game"
        game.save()
        return redirect('game:chat', gameID=gameID)
    return render(request, 'game/createCharacter.html', {'form': form})


@login_required
def create_Game(request):
    if request.method == "POST":
        if Game.objects.filter(user=request.user).count() >= 3:
            return JsonResponse({"message": "User already has 3 games."}, status=202)
        game = Game.objects.create(
            name = "Default_Game_Name",
            setting = "Default_Setting",
            user = request.user
        )
        return JsonResponse({"message": "Game Successfully Created.", "gameID": game.id}, status=200)
    else:
        return JsonResponse({"message": "Invalid request method"}, status=400)
    
@login_required
def chat(request, gameID):
    game = Game.objects.get(id=gameID)
    return render(request, 'game/gamechat.html', {'game': game})

@login_required
def list(request):
    currentUser = request.user
    saved_games = Game.objects.filter(user=currentUser)
    return render(request, 'game/list.html', {'games': saved_games})

@login_required
def detail(request, gameID):
    game = Game.objects.get(id=gameID)
    try:
        user_character = Character.objects.get(game=game, is_user=True)
        return render(request, 'game/gameDetail.html', {'game':game, 'user_character': user_character})
    except Character.DoesNotExist:
        return redirect('game:create_character', gameID=gameID)

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Create your views here.

def redir(request):
    return redirect('start')

def home(request):
    return render(request, 'home/home.html')

@login_required
def start(request):
    return render(request, 'home/start.html')

game/templates/game/createCharacter.html
{% extends 'base.html' %}
{% block body %}
<div class="flex flex-col justify-center items-center min-h-screen">
    <form method="POST" class="rounded-lg max-w-md shadow-md bg-indigo-500 text-black p-6">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Create Character</button>
    </form>
</div>
{% endblock body %}

game/templates/game/gameDetail.html
{% extends 'base.html' %}
{% block body %}
<h1>{{ user_character.name }}</h1>
{% endblock body %}

game/templates/game/gamechat.html
{% extends 'base.html' %}
{% block body %}
<h1>body</h1>
<h1>{{ game.name }}</h1>
{% endblock body %}
{% block script %}
{% endblock script %}

game/templates/game/list.html
{% extends 'base.html' %}
{% block body %}
{% for game in games %}
<div>
    <a href="{% url 'game:detail' gameID=game.id %}">
        <h1 class="text-4xl">
            {{ game.name }}
        </h1>
    </a>
</div>
{% endfor %}
{% endblock body %}

home/templates/home/home.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock title %}
{% block body %}
<div class="flex flex-col items-center justify-center min-h-screen">
    <div class="text-center font-bold text-8xl">APPNAME</div>
    <div class="text-center text-4xl mt-5">Sign in to Start</div>
</div>
{% endblock body %}
{% block script %}

{% endblock script%}

home/templates/home/list.html
{% extends 'base.html' %}
{% block body %}
<div class="flex flex-col items-center justify-center min-h-screen">
    <div class="text-center text-8xl font-bold">Choose Option</div>
    <div class="flex flex-row justify-center mt-5">
        <h1 class="text-4xl text-center">Load Game</h1>
        <button onClick="createGame()">Start Game</button>
    </div>
</div>
{% endblock body %}
{% block script %}
<script>
    async function createGame() {
        const endpointURL = "{% url 'game:create_game' %}"
        try {
            const response = await fetch(endpointURL, {
                method: 'POST',
                headers: {
                    "Content-Type": "application/json",
                    'X-CSRFToken' : '{{ csrf_token }}',
                },
                body: JSON.stringify({"thing": "here"}),
            });
            if (response.ok){
                const data = await response.json()
                console.log(data);
                console.log(response.status)
                const gameID = data.gameID;
                window.location.href = "/games/" + gameID + "/create/";
            } else {
                console.error("Error creating game: ", response.status);  
                console.log(response)
            }
        } catch (error) {
            console.error("Error occured", error);
        }
    }
</script>
{% endblock script%}

home/templates/home/start.html
{% extends 'base.html' %}
{% block body %}
<div class="flex flex-col items-center justify-center min-h-screen">
    <div class="text-center text-8xl font-bold">Knockoff D&D</div>
    <div class="flex flex-row justify-center mt-5">
        <a href="{% url 'game:list' %}">
            <h1 class="text-4xl text-center">Load Game</h1>
        </a>
        <button onClick="createGame()" class="text-4xl ml-5">Start Game</button>
    </div>
</div>
{% endblock body %}
{% block script %}
<script>
    async function createGame() {
        const endpointURL = "{% url 'game:create_game' %}"
        try {
            const response = await fetch(endpointURL, {
                method: 'POST',
                headers: {
                    "Content-Type": "application/json",
                    'X-CSRFToken' : '{{ csrf_token }}',
                },
                body: JSON.stringify({}),
            });
            if (response.ok){
                if (response.status == 202) {
                    window.location.href = "/games/list/"
                    return
                }
                const data = await response.json()
                console.log(data);
                console.log(response.status)
                const gameID = data.gameID;
                window.location.href = "/games/create/" + gameID;
            } else {
                console.error("Error creating game: ", response.status);  
                console.log(response)
            }
        } catch (error) {
            console.error("Error occured", error);
        }
    }
</script>
{% endblock script%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Document{% endblock title %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-indigo-800 text-indigo-400">
    {% block body %}
    {% endblock body %}
</body>
    {% block script %}
    {% endblock script %}
</html>